# Generated by Django 3.2.8 on 2023-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(db_index=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(db_index=True, verbose_name='Время открытия'),
        ),
    ]
