# Generated by Django 3.2.8 on 2023-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20230901_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='building',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Здание'),
        ),
    ]
