# Generated by Django 3.2.8 on 2023-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20230901_1411'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['closing_time', 'opening_time'], name='shops_shop_closing_f659ae_idx'),
        ),
    ]
