# Generated by Django 3.2.8 on 2023-09-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20230901_1422'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_name_400cb4_idx',
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['closing_time'], name='shops_shop_closing_a9d07e_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['opening_time'], name='shops_shop_opening_7898b5_idx'),
        ),
    ]
