# Generated by Django 3.2.8 on 2023-09-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20230901_1424'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_closing_a9d07e_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_opening_7898b5_idx',
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['closing_time', 'opening_time'], name='shops_shop_closing_f659ae_idx'),
        ),
    ]
