# Generated by Django 3.2.8 on 2023-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20230901_1441'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_closing_f659ae_idx',
        ),
        migrations.AlterField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
