# Generated by Django 3.2.8 on 2023-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20230901_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(db_index=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(db_index=True, verbose_name='Время открытия'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['closing_time', 'opening_time'], name='shops_shop_closing_f659ae_idx'),
        ),
    ]
