# Generated by Django 3.2.8 on 2023-09-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_auto_20230903_1333'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['id', 'name'], name='shops_city_id_7eee97_idx'),
        ),
    ]
