# Generated by Django 3.2.8 on 2023-09-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_city_shops_city_id_7eee97_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='shops_city_id_7eee97_idx',
        ),
    ]
